version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: recruitbuddy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: recruitbuddy
      POSTGRES_PASSWORD: recruitbuddy
      POSTGRES_DB: recruitbuddy
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recruitbuddy"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Rust Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recruitbuddy-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://recruitbuddy:recruitbuddy@postgres:5432/recruitbuddy
      RUST_LOG: info
    ports:
      - "8080:8080"

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: recruitbuddy-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data: